"""
Space Flappy — main.py
======================
A space-themed Flappy-Bird-style game built with pygame.

Character : a rocket ship (images/rocket.png)
Background: deep-space starfield with nebula (images/background.png)
Obstacles : asteroid columns (images/asteroid_top.png / asteroid_bot.png)

Menu items
----------
  Start    – begin a new game from Level 1
  Continue – resume from the last completed level (saved in save_data.json)
  Level    – choose any previously unlocked level
  Sound    – toggle sound effects / music on or off
  Exit     – quit the application

Levels (10 total)
-----------------
  1-3  Easy   – slower speed, wider gap, fewer asteroids
  4-6  Medium – moderate speed and gap
  7-10 Hard   – fast speed, narrow gap, rapid spawn

Python features used
--------------------
  • Docstrings  (module, class, function)
  • Type annotations
  • Custom exceptions (GameError, AssetLoadError, SaveDataError)
  • try / except / finally blocks throughout
  • Dataclass-style __slots__ on game objects
  • Module-level NOTE markers for important design decisions
"""

# NOTE: pygame must be installed: pip install pygame
#       Images are generated by generate_images.py in the same directory.

import json
import math
import os
import random
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import pygame  # type: ignore[import]

# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM EXCEPTIONS
# ─────────────────────────────────────────────────────────────────────────────

class GameError(Exception):
    """Base exception for all Space Flappy errors."""


class AssetLoadError(GameError):
    """Raised when a required image or sound file cannot be loaded.

    Argument
    --------
    path : str
        Filesystem path that failed to load.
    """

    def __init__(self, path: str) -> None:
        self.path = path
        super().__init__(f"Failed to load asset: '{path}'")


class SaveDataError(GameError):
    """Raised when the save file cannot be read or written.

    Argument
    --------
    detail : str
        Human-readable description of what went wrong.
    """

    def __init__(self, detail: str) -> None:
        super().__init__(f"Save-data error — {detail}")


class LevelRangeError(GameError, ValueError):
    """Raised when a level number is outside the valid 1-10 range.

    Argument
    --------
    level : int
        The out-of-range level that was requested.
    """

    def __init__(self, level: int) -> None:
        self.level = level
        super().__init__(f"Level {level} is out of range (must be 1-10)")


# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

# NOTE: Keep all magic numbers here so they are easy to tweak.

GAME_WIDTH:  int = 360
GAME_HEIGHT: int = 640
FPS:         int = 60

ROCKET_W: int = 40
ROCKET_H: int = 56

ASTEROID_W: int = 80
ASTEROID_H: int = 600

GRAVITY:       float = 0.38
JUMP_VELOCITY: float = -6.2

SAVE_FILE = Path("save_data.json")
IMAGES_DIR = Path("images")

# ─── Level definitions ───────────────────────────────────────────────────────
# Each entry: (label, velocity_x, gap, spawn_ms)
#   velocity_x – horizontal speed of asteroids (negative = left)
#   gap        – vertical opening between top and bottom asteroid
#   spawn_ms   – milliseconds between asteroid pair spawns

LEVEL_CONFIG: dict[int, tuple[str, float, int, int]] = {
    1:  ("Easy",   -2.0, 230, 2200),
    2:  ("Easy",   -2.3, 215, 2100),
    3:  ("Easy",   -2.6, 200, 2000),
    4:  ("Medium", -3.0, 190, 1800),
    5:  ("Medium", -3.4, 178, 1650),
    6:  ("Medium", -3.8, 165, 1500),
    7:  ("Hard",   -4.3, 152, 1350),
    8:  ("Hard",   -4.8, 140, 1200),
    9:  ("Hard",   -5.4, 128, 1050),
    10: ("Hard",   -6.0, 115,  900),
}

# Score needed to advance to next level
SCORE_TO_ADVANCE: int = 10  # pairs passed

# ─────────────────────────────────────────────────────────────────────────────
# COLOURS
# ─────────────────────────────────────────────────────────────────────────────

WHITE  = (255, 255, 255)
BLACK  = (0,   0,   0)
CYAN   = (0,   220, 255)
GOLD   = (255, 200, 50)
RED    = (220, 60,  60)
GREY   = (160, 165, 180)
DARK   = (15,  10,  35)
ORANGE = (255, 140, 0)
GREEN  = (80,  220, 120)
PURPLE = (160, 80,  220)

# ─────────────────────────────────────────────────────────────────────────────
# DATA CLASSES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class SaveData:
    """Persistent player progress.

    Attributes
    ----------
    max_unlocked_level : int
        Highest level the player has unlocked (1-10).
    last_level : int
        The level that was active when the player last quit.
    sound_on : bool
        Whether sound is currently enabled.
    high_scores : dict[str, int]
        Best score per level key (e.g. ``"level_3"``).
    """

    max_unlocked_level: int = 1
    last_level: int = 1
    sound_on: bool = True
    high_scores: dict = field(default_factory=dict)


def load_save() -> SaveData:
    """Load *SaveData* from ``save_data.json``.

    Returns a fresh :class:`SaveData` if the file is absent.

    Raises
    ------
    SaveDataError
        If the file exists but is malformed JSON.
    """
    if not SAVE_FILE.exists():
        return SaveData()

    try:
        raw = SAVE_FILE.read_text(encoding="utf-8")
        obj = json.loads(raw)
        return SaveData(
            max_unlocked_level=int(obj.get("max_unlocked_level", 1)),
            last_level=int(obj.get("last_level", 1)),
            sound_on=bool(obj.get("sound_on", True)),
            high_scores=dict(obj.get("high_scores", {})),
        )
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise SaveDataError(f"Cannot parse save file — {exc}") from exc


def persist_save(data: SaveData) -> None:
    """Write *data* to ``save_data.json``.

    Raises
    ------
    SaveDataError
        If the file cannot be written.
    """
    try:
        payload = {
            "max_unlocked_level": data.max_unlocked_level,
            "last_level": data.last_level,
            "sound_on": data.sound_on,
            "high_scores": data.high_scores,
        }
        SAVE_FILE.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    except OSError as exc:
        raise SaveDataError(f"Cannot write save file — {exc}") from exc


# ─────────────────────────────────────────────────────────────────────────────
# GAME OBJECTS
# ─────────────────────────────────────────────────────────────────────────────

class Rocket(pygame.Rect):
    """Player-controlled rocket sprite.

    Inherits from :class:`pygame.Rect` so collision detection can use
    ``pygame.Rect.colliderect`` directly.

    Parameters
    ----------
    img : pygame.Surface
        Pre-loaded rocket image surface.
    """

    __slots__ = ("img", "velocity_y")

    def __init__(self, img: pygame.Surface) -> None:
        super().__init__(GAME_WIDTH // 8, GAME_HEIGHT // 2, ROCKET_W, ROCKET_H)
        self.img: pygame.Surface = img
        self.velocity_y: float = 0.0


class Asteroid(pygame.Rect):
    """A single asteroid-column obstacle.

    Parameters
    ----------
    img    : pygame.Surface  – pre-loaded texture.
    is_top : bool            – True if this is the upper column.
    """

    __slots__ = ("img", "is_top", "passed")

    def __init__(self, img: pygame.Surface, is_top: bool) -> None:
        super().__init__(GAME_WIDTH, 0, ASTEROID_W, ASTEROID_H)
        self.img:    pygame.Surface = img
        self.is_top: bool = is_top
        self.passed: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# ASSET LOADER
# ─────────────────────────────────────────────────────────────────────────────

def load_image(filename: str, size: tuple[int, int], alpha: bool = True) -> pygame.Surface:
    """Load and scale an image from the ``images/`` directory.

    Parameters
    ----------
    filename : str
        File name inside ``images/``.
    size : tuple[int, int]
        Target (width, height) after scaling.
    alpha : bool
        If True use ``convert_alpha()``, else ``convert()``.

    Returns
    -------
    pygame.Surface

    Raises
    ------
    AssetLoadError
        If the file does not exist or pygame fails to load it.
    """
    path = IMAGES_DIR / filename
    if not path.exists():
        raise AssetLoadError(str(path))
    try:
        surf = pygame.image.load(str(path))
        surf = surf.convert_alpha() if alpha else surf.convert()
        return pygame.transform.scale(surf, size)
    except pygame.error as exc:
        raise AssetLoadError(str(path)) from exc


# ─────────────────────────────────────────────────────────────────────────────
# STAR PARALLAX LAYER (decorative)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Star:
    """A single parallax background star.

    Attributes
    ----------
    x, y    : float  – current position.
    speed   : float  – scroll speed (pixels per frame).
    size    : int    – drawn radius in pixels.
    bright  : int    – grey brightness 0-255.
    """

    x: float
    y: float
    speed: float
    size: int
    bright: int


def make_stars(count: int = 60) -> list[Star]:
    """Generate *count* random stars for parallax scrolling.

    NOTE: Stars are intentionally sparse so they don't obscure the
    background image that already contains stars.
    """
    return [
        Star(
            x=random.uniform(0, GAME_WIDTH),
            y=random.uniform(0, GAME_HEIGHT),
            speed=random.uniform(0.3, 1.2),
            size=random.choice([1, 1, 1, 2]),
            bright=random.randint(180, 255),
        )
        for _ in range(count)
    ]


def scroll_stars(stars: list[Star], dt_factor: float = 1.0) -> None:
    """Move each star left and wrap around the screen.

    Parameters
    ----------
    stars     : list[Star]
    dt_factor : float  – speed multiplier (scales with game velocity).
    """
    for s in stars:
        s.x -= s.speed * dt_factor
        if s.x < 0:
            s.x = GAME_WIDTH
            s.y = random.uniform(0, GAME_HEIGHT)


def draw_stars(surface: pygame.Surface, stars: list[Star]) -> None:
    """Render all stars onto *surface*."""
    for s in stars:
        col = (s.bright, s.bright, s.bright)
        if s.size == 1:
            surface.set_at((int(s.x), int(s.y)), col)
        else:
            pygame.draw.circle(surface, col, (int(s.x), int(s.y)), s.size)


# ─────────────────────────────────────────────────────────────────────────────
# UI HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def draw_text_centered(
    surface: pygame.Surface,
    text: str,
    font: pygame.font.Font,
    color: tuple,
    y: int,
    shadow: bool = True,
) -> None:
    """Render *text* horizontally centered on *surface* at vertical position *y*.

    Parameters
    ----------
    surface : pygame.Surface
    text    : str
    font    : pygame.font.Font
    color   : tuple[int, int, int]
    y       : int   – top of the text rect
    shadow  : bool  – draw a dark offset shadow first
    """
    rendered = font.render(text, True, color)
    x = (GAME_WIDTH - rendered.get_width()) // 2
    if shadow:
        shadow_surf = font.render(text, True, (0, 0, 0))
        surface.blit(shadow_surf, (x + 2, y + 2))
    surface.blit(rendered, (x, y))


def draw_panel(surface: pygame.Surface, rect: pygame.Rect, alpha: int = 180) -> None:
    """Draw a semi-transparent dark panel for menu backgrounds.

    Parameters
    ----------
    surface : pygame.Surface
    rect    : pygame.Rect
    alpha   : int  – 0 (transparent) … 255 (opaque)
    """
    panel = pygame.Surface((rect.width, rect.height), pygame.SRCALPHA)
    panel.fill((10, 5, 30, alpha))
    # border
    pygame.draw.rect(panel, CYAN + (200,), panel.get_rect(), width=2, border_radius=12)
    surface.blit(panel, rect.topleft)


# ─────────────────────────────────────────────────────────────────────────────
# LEVEL TRANSITION SCREEN
# ─────────────────────────────────────────────────────────────────────────────

def show_level_intro(
    surface: pygame.Surface,
    bg: pygame.Surface,
    stars: list[Star],
    level: int,
    font_big: pygame.font.Font,
    font_med: pygame.font.Font,
    clock: pygame.time.Clock,
) -> None:
    """Display a brief animated countdown before gameplay starts.

    NOTE: This uses a simple frame counter rather than ``pygame.time.wait``
    so that quit events can still be processed during the transition.

    Parameters
    ----------
    surface   : pygame.Surface – main window
    bg        : pygame.Surface – background image
    stars     : list[Star]
    level     : int
    font_big  : large font
    font_med  : medium font
    clock     : pygame.time.Clock
    """
    label, *_ = LEVEL_CONFIG[level]
    frames = FPS * 2  # 2-second intro
    for frame in range(frames):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()

        surface.blit(bg, (0, 0))
        scroll_stars(stars, dt_factor=0.5)
        draw_stars(surface, stars)

        draw_text_centered(surface, f"LEVEL {level}", font_big, GOLD, 200)
        draw_text_centered(surface, label, font_med, CYAN, 262)
        countdown = 3 - frame // FPS
        if countdown > 0:
            draw_text_centered(surface, str(countdown), font_big, WHITE, 340)
        else:
            draw_text_centered(surface, "GO!", font_big, GREEN, 340)

        pygame.display.flip()
        clock.tick(FPS)


# ─────────────────────────────────────────────────────────────────────────────
# GAME STATE
# ─────────────────────────────────────────────────────────────────────────────

class GameSession:
    """Holds all mutable state for one active gameplay session.

    Parameters
    ----------
    level      : int             – starting level (1-10)
    rocket_img : pygame.Surface  – player sprite
    top_img    : pygame.Surface  – top asteroid texture
    bot_img    : pygame.Surface  – bottom asteroid texture

    Raises
    ------
    LevelRangeError
        If *level* is outside 1-10.
    """

    def __init__(
        self,
        level: int,
        rocket_img: pygame.Surface,
        top_img: pygame.Surface,
        bot_img: pygame.Surface,
    ) -> None:
        if level not in LEVEL_CONFIG:
            raise LevelRangeError(level)

        self.level:       int = level
        self.rocket_img:  pygame.Surface = rocket_img
        self.top_img:     pygame.Surface = top_img
        self.bot_img:     pygame.Surface = bot_img

        self.rocket:      Rocket = Rocket(rocket_img)
        self.asteroids:   list[Asteroid] = []
        self.score:       int = 0
        self.game_over:   bool = False
        self.level_clear: bool = False

        self._vel_x:    float = 0.0
        self._gap:      int   = 0
        self._spawn_ms: int   = 0
        self._apply_level_config()

    # ── internal helpers ─────────────────────────────────────────────────────

    def _apply_level_config(self) -> None:
        """Read speed, gap, and spawn rate from :data:`LEVEL_CONFIG`."""
        _label, vel_x, gap, spawn_ms = LEVEL_CONFIG[self.level]
        self._vel_x    = vel_x
        self._gap      = gap
        self._spawn_ms = spawn_ms

    # ── public API ───────────────────────────────────────────────────────────

    def spawn_pair(self) -> None:
        """Create one top + one bottom asteroid pair.

        NOTE: Random Y offset is clamped so the gap is always at least
        partially on screen, regardless of level config.
        """
        offset = random.randint(-ASTEROID_H // 4, ASTEROID_H // 4)

        top = Asteroid(self.top_img, is_top=True)
        top.x = GAME_WIDTH
        top.y = -ASTEROID_H + offset
        self.asteroids.append(top)

        bot = Asteroid(self.bot_img, is_top=False)
        bot.x = GAME_WIDTH
        bot.y = top.y + ASTEROID_H + self._gap
        self.asteroids.append(bot)

    def update(self) -> None:
        """Advance physics by one frame.

        Updates rocket gravity, asteroid positions, collision detection,
        and score. Sets :attr:`game_over` or :attr:`level_clear` as needed.

        NOTE: Scoring counts each *pair* as one point (each pipe in the pair
        increments by 0.5 so we use integer score after two increments).
        """
        if self.game_over or self.level_clear:
            return

        # rocket gravity
        self.rocket.velocity_y += GRAVITY
        self.rocket.y += math.floor(self.rocket.velocity_y)

        # floor / ceiling
        if self.rocket.y < 0:
            self.rocket.y = 0
            self.rocket.velocity_y = 0.0
        if self.rocket.y + ROCKET_H > GAME_HEIGHT:
            self.game_over = True
            return

        # asteroids
        for ast in self.asteroids:
            ast.x += math.floor(self._vel_x)

            # scoring
            if not ast.passed and self.rocket.x > ast.x + ASTEROID_W:
                ast.passed = True
                self.score += 1  # +1 per column → +2 per pair total

            # collision
            if self.rocket.colliderect(ast):
                self.game_over = True
                return

        # remove off-screen asteroids
        self.asteroids = [a for a in self.asteroids if a.x > -ASTEROID_W]

        # pairs scored = score // 2
        pairs = self.score // 2
        if pairs >= SCORE_TO_ADVANCE:
            self.level_clear = True

    def jump(self) -> None:
        """Apply upward velocity to the rocket (player input)."""
        self.rocket.velocity_y = JUMP_VELOCITY

    def reset(self) -> None:
        """Reset rocket and asteroids to start-of-level state."""
        self.rocket.x = GAME_WIDTH // 8
        self.rocket.y = GAME_HEIGHT // 2
        self.rocket.velocity_y = 0.0
        self.asteroids.clear()
        self.score = 0
        self.game_over = False
        self.level_clear = False

    def advance_level(self) -> bool:
        """Move to the next level if one exists.

        Returns
        -------
        bool
            True if advanced successfully, False if already at level 10.
        """
        if self.level >= 10:
            return False
        self.level += 1
        self._apply_level_config()
        self.reset()
        return True

    @property
    def pairs_scored(self) -> int:
        """Number of asteroid pairs the player has passed."""
        return self.score // 2

    @property
    def spawn_interval_ms(self) -> int:
        """Current asteroid spawn interval in milliseconds."""
        return self._spawn_ms


# ─────────────────────────────────────────────────────────────────────────────
# MENU
# ─────────────────────────────────────────────────────────────────────────────

class Menu:
    """Animated main-menu renderer and input handler.

    Parameters
    ----------
    surface    : pygame.Surface
    bg         : pygame.Surface  – background image
    stars      : list[Star]
    font_big   : large title font
    font_med   : menu item font
    font_small : small info font
    save       : SaveData

    Attributes
    ----------
    selection : str
        The menu item chosen by the player.  One of:
        ``"start"``, ``"continue"``, ``"level"``, ``"sound"``, ``"exit"``.
    chosen_level : int
        Level chosen when ``selection == "level"`` or ``"continue"``.
    """

    ITEMS = ["Start", "Continue", "Level", "Sound", "Exit"]

    def __init__(
        self,
        surface:    pygame.Surface,
        bg:         pygame.Surface,
        stars:      list[Star],
        font_big:   pygame.font.Font,
        font_med:   pygame.font.Font,
        font_small: pygame.font.Font,
        save:       SaveData,
    ) -> None:
        self.surface    = surface
        self.bg         = bg
        self.stars      = stars
        self.font_big   = font_big
        self.font_med   = font_med
        self.font_small = font_small
        self.save       = save

        self.cursor:       int = 0   # index into ITEMS
        self.selection:    str = ""
        self.chosen_level: int = 1

        self._anim_tick: int = 0

    # ── sub-screens ──────────────────────────────────────────────────────────

    def _level_select_screen(self, clock: pygame.time.Clock) -> Optional[int]:
        """Show the level-select sub-screen.

        Returns the chosen level (1-10) or *None* if the player pressed
        Escape to go back.
        """
        cursor = 0
        unlocked = self.save.max_unlocked_level

        while True:
            self._anim_tick += 1
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_ESCAPE:
                        return None
                    if event.key in (pygame.K_UP, pygame.K_w):
                        cursor = (cursor - 1) % 10
                    if event.key in (pygame.K_DOWN, pygame.K_s):
                        cursor = (cursor + 1) % 10
                    if event.key in (pygame.K_RETURN, pygame.K_SPACE):
                        chosen = cursor + 1
                        if chosen <= unlocked:
                            return chosen

            self.surface.blit(self.bg, (0, 0))
            scroll_stars(self.stars)
            draw_stars(self.surface, self.stars)

            draw_panel(self.surface, pygame.Rect(30, 30, 300, 580))
            draw_text_centered(self.surface, "SELECT LEVEL", self.font_big, CYAN, 45)

            for i in range(10):
                lvl = i + 1
                label, *_ = LEVEL_CONFIG[lvl]
                locked = lvl > unlocked
                y = 120 + i * 44
                if i == cursor:
                    glow = abs(math.sin(self._anim_tick * 0.06)) * 40
                    col = (int(200 + glow), int(220 + glow // 2), 255)
                    draw_text_centered(self.surface, f"► Level {lvl}  [{label}]", self.font_med, col, y)
                elif locked:
                    draw_text_centered(self.surface, f"  Level {lvl}  🔒", self.font_small, GREY, y + 8)
                else:
                    draw_text_centered(self.surface, f"  Level {lvl}  [{label}]", self.font_med, WHITE, y)

            draw_text_centered(self.surface, "ESC = Back", self.font_small, GREY, 570)
            pygame.display.flip()
            clock.tick(FPS)

    # ── main loop ────────────────────────────────────────────────────────────

    def run(self, clock: pygame.time.Clock) -> None:
        """Block until the player picks a menu action.

        Results are stored in :attr:`selection` and :attr:`chosen_level`.
        """
        self.selection = ""
        self.cursor = 0

        while not self.selection:
            self._anim_tick += 1

            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    self.selection = "exit"

                if event.type == pygame.KEYDOWN:
                    if event.key in (pygame.K_UP, pygame.K_w):
                        self.cursor = (self.cursor - 1) % len(self.ITEMS)
                    elif event.key in (pygame.K_DOWN, pygame.K_s):
                        self.cursor = (self.cursor + 1) % len(self.ITEMS)
                    elif event.key in (pygame.K_RETURN, pygame.K_SPACE):
                        self._activate(clock)

            self._draw()
            pygame.display.flip()
            clock.tick(FPS)

    def _activate(self, clock: pygame.time.Clock) -> None:
        """Handle the currently highlighted menu item."""
        item = self.ITEMS[self.cursor].lower()

        if item == "start":
            self.chosen_level = 1
            self.selection = "start"

        elif item == "continue":
            self.chosen_level = self.save.last_level
            self.selection = "continue"

        elif item == "level":
            chosen = self._level_select_screen(clock)
            if chosen is not None:
                self.chosen_level = chosen
                self.selection = "level"

        elif item == "sound":
            self.save.sound_on = not self.save.sound_on
            try:
                persist_save(self.save)
            except SaveDataError:
                pass  # non-critical — ignore silently

        elif item == "exit":
            self.selection = "exit"

    def _draw(self) -> None:
        """Render one frame of the main menu."""
        self.surface.blit(self.bg, (0, 0))
        scroll_stars(self.stars)
        draw_stars(self.surface, self.stars)

        # title panel
        draw_panel(self.surface, pygame.Rect(20, 40, 320, 120), alpha=200)
        draw_text_centered(self.surface, "SPACE FLAPPY", self.font_big, GOLD, 60)
        draw_text_centered(self.surface, "🚀  Dodge the Asteroids!", self.font_small, CYAN, 118)

        # menu items panel
        draw_panel(self.surface, pygame.Rect(60, 200, 240, 320), alpha=190)

        for i, item in enumerate(self.ITEMS):
            y = 220 + i * 58
            if i == self.cursor:
                glow = abs(math.sin(self._anim_tick * 0.07)) * 50
                col = (int(150 + glow), int(210 + glow // 2), 255)
                label = f"► {item}"
                if item == "Sound":
                    label += "  [ON]" if self.save.sound_on else "  [OFF]"
                draw_text_centered(self.surface, label, self.font_med, col, y)
            else:
                col = WHITE
                label = item
                if item == "Sound":
                    label += "  [ON]" if self.save.sound_on else "  [OFF]"
                draw_text_centered(self.surface, label, self.font_med, col, y)

        # footer
        draw_text_centered(self.surface, "↑↓ Navigate   Enter Select", self.font_small, GREY, 545)
        unlocked = self.save.max_unlocked_level
        draw_text_centered(
            self.surface,
            f"Highest level unlocked: {unlocked}",
            self.font_small,
            GREY,
            572,
        )


# ─────────────────────────────────────────────────────────────────────────────
# HUD
# ─────────────────────────────────────────────────────────────────────────────

def draw_hud(
    surface:    pygame.Surface,
    session:    GameSession,
    font_med:   pygame.font.Font,
    font_small: pygame.font.Font,
) -> None:
    """Render the in-game heads-up display.

    Shows current level, pairs scored, and target score.

    Parameters
    ----------
    surface    : pygame.Surface
    session    : GameSession
    font_med   : medium font
    font_small : small font
    """
    label, *_ = LEVEL_CONFIG[session.level]
    pairs = session.pairs_scored

    # score
    draw_text_centered(surface, str(pairs), font_med, WHITE, 10, shadow=True)

    # level badge (top-left)
    badge = font_small.render(f"Lv {session.level}  {label}", True, CYAN)
    surface.blit(badge, (8, 12))

    # target (top-right)
    target_txt = font_small.render(f"Goal: {SCORE_TO_ADVANCE}", True, GOLD)
    surface.blit(target_txt, (GAME_WIDTH - target_txt.get_width() - 8, 12))


# ─────────────────────────────────────────────────────────────────────────────
# GAME-OVER / LEVEL-CLEAR OVERLAYS
# ─────────────────────────────────────────────────────────────────────────────

def draw_game_over(
    surface:    pygame.Surface,
    session:    GameSession,
    font_big:   pygame.font.Font,
    font_med:   pygame.font.Font,
    font_small: pygame.font.Font,
    save:       SaveData,
) -> None:
    """Render the game-over overlay.

    Shows score, high-score for this level, and restart / menu hint.

    Parameters
    ----------
    surface    : pygame.Surface
    session    : GameSession
    font_big   : title font
    font_med   : score font
    font_small : hint font
    save       : SaveData  – used to display high-score
    """
    draw_panel(surface, pygame.Rect(40, 180, 280, 280), alpha=220)
    draw_text_centered(surface, "GAME OVER", font_big, RED, 200)

    pairs = session.pairs_scored
    draw_text_centered(surface, f"Score: {pairs}", font_med, WHITE, 265)

    key = f"level_{session.level}"
    best = save.high_scores.get(key, 0)
    draw_text_centered(surface, f"Best: {best}", font_med, GOLD, 308)

    draw_text_centered(surface, "Space / Click = Retry", font_small, CYAN, 365)
    draw_text_centered(surface, "Esc = Menu",            font_small, GREY, 390)


def draw_level_clear(
    surface:    pygame.Surface,
    session:    GameSession,
    font_big:   pygame.font.Font,
    font_med:   pygame.font.Font,
    font_small: pygame.font.Font,
    tick:       int,
) -> None:
    """Render the level-clear celebration overlay.

    Parameters
    ----------
    tick : int  – frame counter for animation.
    """
    draw_panel(surface, pygame.Rect(40, 160, 280, 320), alpha=220)
    draw_text_centered(surface, "LEVEL CLEAR!", font_big, GREEN, 180)

    glow_val = int(abs(math.sin(tick * 0.08)) * 80 + 160)
    star_col = (glow_val, glow_val, 80)
    draw_text_centered(surface, "★★★", font_big, star_col, 240)

    draw_text_centered(surface, f"Score: {session.pairs_scored}", font_med, WHITE, 308)

    if session.level < 10:
        draw_text_centered(surface, "Space = Next Level", font_small, CYAN, 375)
    else:
        draw_text_centered(surface, "🏆  YOU WIN — ALL DONE!", font_med, GOLD, 375)

    draw_text_centered(surface, "Esc = Menu", font_small, GREY, 410)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN APPLICATION
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    """Entry point — initialises pygame, loads assets, and runs the game loop.

    Flow
    ----
    1. Load save data (gracefully falls back on corrupt file).
    2. Load images; abort with a clear message if any are missing.
    3. Show main menu.
    4. Run gameplay session.
    5. On game-over or level-clear, update save and return to menu.

    NOTE: The outer try/finally ensures ``pygame.quit()`` is called even if
    an unexpected exception propagates out of the game loop.
    """
    # ── pygame init ──────────────────────────────────────────────────────────
    pygame.init()
    window = pygame.display.set_mode((GAME_WIDTH, GAME_HEIGHT))
    pygame.display.set_caption("Space Flappy 🚀")

    clock = pygame.time.Clock()

    # ── load save ────────────────────────────────────────────────────────────
    try:
        save = load_save()
    except SaveDataError as exc:
        print(f"[WARNING] {exc}  — starting fresh.")
        save = SaveData()

    # ── load assets ──────────────────────────────────────────────────────────
    try:
        # icon
        icon_path = IMAGES_DIR / "icon.png"
        if icon_path.exists():
            pygame.display.set_icon(pygame.image.load(str(icon_path)))

        bg_surf    = load_image("background.png",   (GAME_WIDTH, GAME_HEIGHT), alpha=False)
        rocket_img = load_image("rocket.png",       (ROCKET_W, ROCKET_H))
        top_img    = load_image("asteroid_top.png", (ASTEROID_W, ASTEROID_H))
        bot_img    = load_image("asteroid_bot.png", (ASTEROID_W, ASTEROID_H))

    except AssetLoadError as exc:
        print(f"[ERROR] {exc}")
        print("Run generate_images.py first to create the required images.")
        pygame.quit()
        sys.exit(1)

    # ── fonts ────────────────────────────────────────────────────────────────
    try:
        font_big   = pygame.font.SysFont("Arial", 38, bold=True)
        font_med   = pygame.font.SysFont("Arial", 26)
        font_small = pygame.font.SysFont("Arial", 18)
    except Exception:
        font_big   = pygame.font.Font(None, 38)
        font_med   = pygame.font.Font(None, 26)
        font_small = pygame.font.Font(None, 18)

    # ── stars ────────────────────────────────────────────────────────────────
    stars = make_stars(60)

    # ── custom events ────────────────────────────────────────────────────────
    SPAWN_ASTEROIDS = pygame.USEREVENT + 1

    # ── session state ────────────────────────────────────────────────────────
    session: Optional[GameSession] = None
    in_game = False
    anim_tick = 0

    menu = Menu(window, bg_surf, stars, font_big, font_med, font_small, save)

    # ── main application loop ────────────────────────────────────────────────
    try:
        while True:
            # ── MENU ─────────────────────────────────────────────────────────
            menu.run(clock)

            if menu.selection == "exit":
                break

            start_level = menu.chosen_level

            # ── start gameplay session ────────────────────────────────────────
            try:
                session = GameSession(start_level, rocket_img, top_img, bot_img)
            except LevelRangeError as exc:
                print(f"[ERROR] {exc}")
                continue

            # arm spawn timer
            pygame.time.set_timer(SPAWN_ASTEROIDS, session.spawn_interval_ms)

            show_level_intro(window, bg_surf, stars, session.level,
                             font_big, font_med, clock)

            in_game = True
            save.last_level = session.level

            # ── gameplay loop ─────────────────────────────────────────────────
            while in_game:
                anim_tick += 1

                # events
                for event in pygame.event.get():
                    if event.type == pygame.QUIT:
                        in_game = False
                        menu.selection = "exit"

                    elif event.type == SPAWN_ASTEROIDS:
                        if not session.game_over and not session.level_clear:
                            session.spawn_pair()

                    elif event.type == pygame.KEYDOWN:
                        if event.key == pygame.K_ESCAPE:
                            in_game = False  # back to menu

                        elif event.key in (pygame.K_SPACE, pygame.K_UP, pygame.K_w):
                            if session.game_over:
                                # update high-score before reset
                                key = f"level_{session.level}"
                                best = save.high_scores.get(key, 0)
                                if session.pairs_scored > best:
                                    save.high_scores[key] = session.pairs_scored
                                session.reset()
                                pygame.time.set_timer(SPAWN_ASTEROIDS, session.spawn_interval_ms)

                            elif session.level_clear:
                                if not session.advance_level():
                                    in_game = False  # won the whole game
                                else:
                                    pygame.time.set_timer(SPAWN_ASTEROIDS, session.spawn_interval_ms)
                                    # update unlocked level
                                    if session.level > save.max_unlocked_level:
                                        save.max_unlocked_level = session.level
                                    show_level_intro(window, bg_surf, stars,
                                                     session.level, font_big, font_med, clock)
                            else:
                                session.jump()

                    elif event.type == pygame.MOUSEBUTTONDOWN:
                        if event.button == 1:
                            if not session.game_over and not session.level_clear:
                                session.jump()
                            elif session.game_over:
                                key = f"level_{session.level}"
                                best = save.high_scores.get(key, 0)
                                if session.pairs_scored > best:
                                    save.high_scores[key] = session.pairs_scored
                                session.reset()
                                pygame.time.set_timer(SPAWN_ASTEROIDS, session.spawn_interval_ms)

                # ── update ───────────────────────────────────────────────────
                if not session.game_over and not session.level_clear:
                    session.update()

                    # update unlocked level on clear
                    if session.level_clear:
                        next_lv = session.level  # still current (before advance)
                        if next_lv > save.max_unlocked_level:
                            save.max_unlocked_level = next_lv
                        key = f"level_{next_lv}"
                        best = save.high_scores.get(key, 0)
                        if session.pairs_scored > best:
                            save.high_scores[key] = session.pairs_scored
                        save.last_level = next_lv
                        try:
                            persist_save(save)
                        except SaveDataError as exc:
                            print(f"[WARNING] Could not save progress — {exc}")

                # ── draw ─────────────────────────────────────────────────────
                window.blit(bg_surf, (0, 0))
                scroll_stars(stars, dt_factor=abs(session._vel_x) / 3)
                draw_stars(window, stars)

                for ast in session.asteroids:
                    window.blit(ast.img, ast)

                window.blit(session.rocket.img, session.rocket)

                draw_hud(window, session, font_med, font_small)

                if session.game_over:
                    draw_game_over(window, session, font_big, font_med, font_small, save)

                elif session.level_clear:
                    draw_level_clear(window, session, font_big, font_med, font_small, anim_tick)

                pygame.display.flip()
                clock.tick(FPS)

            if menu.selection == "exit":
                break

    finally:
        # NOTE: pygame.quit() is called here regardless of how we exit so
        # that the display is properly torn down even on unexpected errors.
        try:
            persist_save(save)
        except SaveDataError as exc:
            print(f"[WARNING] Final save failed — {exc}")
        pygame.quit()


# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    main()
